### ISSUE TITLE
no task file

### ISSUE THREAD

**Issue by jijiking-hh** [bairuofei/sampling_ltl_planning#3]
Hello, I see that there is a missing file in the warehouse for setting global task requirements. The simulation task is manually set rather than solved. May I ask if the author can provide task input for generating the results displayed in the simulation? I am very  appreciate

**Comment by bairuofei** [comment]
Thanks for your interest and the question. The `simulation.py` is only used for visualization, not for solving the planning problem. That's why you may find the task sequences of the robots are manually set in the `simulation.py`, which is actually obtained by calling the planner in `clasc_ltl_planning.py` or `samp_ltl_planning.py`.

However, I think it will not be difficult to forward the output from the planner to `simulation.py`. For the LTL specification corresponding to the `5-sim.gif`, I cannot publicly provide the original task specification. But, you can easily define your own task specifications by following the instructions in [README](https://github.com/bairuofei/sampling_ltl_planning#format-of-task-specification).

**Comment by jijiking-hh** [comment]
Thank you for your reply. I fully understand and respect your inability to disclose the original task files. If possible, can you provide an example of a multi machine task with practical implications (the examples in readme seem to be unsolvable and have unknown meanings)? This may be very troublesome for you, but it will be of great help to beginners. Thank you very much if possible.

Also, I have always felt that your code does not correspond to the paper in Readme. Do you have any recommended references?

 
笔记

**Comment by jijiking-hh** [comment]
Sorry, I haven't noticed that your repository has corresponding IROS papers that you have published. But the content in the warehouse should not correspond to your paper, is it just a baseline?

**Comment by bairuofei** [comment]
> If possible, can you provide an example of a multi machine task with practical implications (the examples in readme seem to be unsolvable and have unknown meanings)?

I have updated a very simple example [here](https://github.com/bairuofei/sampling_ltl_planning#format-of-task-specification). If you still feel confused, you may need to read related papers to understand the concept of atom propositions, and LTL specification.

> But the content in the warehouse should not correspond to your paper, is it just a baseline?

You are right. This repo only provides the baseline methods to solve the multi-robot LTL planning problem. The recommended IROS paper considers a slightly different problem setting from this repo, but you can still look through it to better understand the concept of LTL formulas.
